In [1]:
import numpy as np

In [2]:
import pandas as pd

1.     Create a 5x7 NumPy array filled with random numbers. Use fancy indexing to access the following entries (row, col): (1,3),(4,5),(3,2), and (0,6).

In [3]:
array = np.random.randint(10,90,(5,7))

In [4]:
array

array([[75, 30, 84, 27, 89, 38, 57],
       [21, 67, 16, 88, 85, 67, 74],
       [24, 31, 65, 14, 10, 14, 45],
       [65, 20, 15, 43, 54, 89, 31],
       [12, 12, 72, 89, 60, 67, 65]])

In [5]:
array[1,3]

88

In [6]:
array[4,5]


67

In [7]:
array[3,2]

15

In [8]:
array[0,6]

57

2.     Explain what np.newxis does and provide an example of how one might use it.



In [9]:
#np.newxis is used to increse the dimension of the array by one. Thus, a 1D array will become a 2D array. An example of it in use is in broadcasting.

In [10]:
 x1 = np.array([1, 2, 3, 4, 5])
 x2 = np.array([5, 4, 3])
 #if you try and add these you will get a value error... these are different dimensional arrays... thus 
x1_new = x1[:, np.newaxis]
x1_new + x2

array([[ 6,  5,  4],
       [ 7,  6,  5],
       [ 8,  7,  6],
       [ 9,  8,  7],
       [10,  9,  8]])

3.     What sorting method does np.sort use and what is its runtime complexity (Big-O)? What does this mean?

In [11]:
#by default numpy uses quicksort, but mergesort and heapsort are also avaliable

# Quicksort has a worst case Big O notation of O(n^2)and best case of O(nlogn)

#This means that the excecution time/space ("describing how the number of operations required for an algorithm scales as the input grows in size") used is either O(n^2) to O(nlogn).

4.     Given the following NumPy array: [4,1,5,2,7,3], what are the indices of the sorted order?



In [12]:
x = np.array([4,1,5,2,7,3])

In [13]:
#gives indices of sorted order
np.argsort(x)

array([1, 3, 5, 0, 2, 4], dtype=int64)

5.     Using the array from #1, sort the columns.



In [14]:
# sort each column of array
np.sort(array, axis=0)

array([[12, 12, 15, 14, 10, 14, 31],
       [21, 20, 16, 27, 54, 38, 45],
       [24, 30, 65, 43, 60, 67, 57],
       [65, 31, 72, 88, 85, 67, 65],
       [75, 67, 84, 89, 89, 89, 74]])

6.     Using the array from #1, sort the rows.



In [15]:
# sort each row of array
np.sort(array, axis=1)

array([[27, 30, 38, 57, 75, 84, 89],
       [16, 21, 67, 67, 74, 85, 88],
       [10, 14, 14, 24, 31, 45, 65],
       [15, 20, 31, 43, 54, 65, 89],
       [12, 12, 60, 65, 67, 72, 89]])

7.     How is a structured array different from a traditional NumPy array, and why might one use it?

In [16]:
#One might use a traditional numpy array if the data is represented by a homogeneous array of values where a structured array provides efficient storage for compound, heterogeneous data. For example, if you have three arrays that are related but are seperate one can structure the array so it is more workable.

8.     Complete the following exercise – activity created by Guilherme Samora.



a.     Import two datasets: cars1 and cars2.



In [17]:
cars1 = pd.read_csv('../csv_files/cars1.csv')  
cars2 = pd.read_csv('../csv_files/cars2.csv')  

b.     Print the top five rows of each.



In [18]:
cars1.head()

mpg  cylinders  displacement horsepower  weight  acceleration  model  \
0  18.0          8           307        130    3504          12.0     70   
1  15.0          8           350        165    3693          11.5     70   
2  18.0          8           318        150    3436          11.0     70   
3  16.0          8           304        150    3433          12.0     70   
4  17.0          8           302        140    3449          10.5     70   

   origin                        car  Unnamed: 9  Unnamed: 10  Unnamed: 11  \
0       1  chevrolet chevelle malibu         NaN          NaN          NaN   
1       1          buick skylark 320         NaN          NaN          NaN   
2       1         plymouth satellite         NaN          NaN          NaN   
3       1              amc rebel sst         NaN          NaN          NaN   
4       1                ford torino         NaN          NaN          NaN   

   Unnamed: 12  Unnamed: 13  
0          NaN          NaN  
1          NaN          NaN  
2          NaN          NaN  
3          NaN          NaN  
4          NaN          NaN

In [19]:
cars2.head()

mpg  cylinders  displacement horsepower  weight  acceleration  model  \
0  33.0          4            91         53    1795          17.4     76   
1  20.0          6           225        100    3651          17.7     76   
2  18.0          6           250         78    3574          21.0     76   
3  18.5          6           250        110    3645          16.2     76   
4  17.5          6           258         95    3193          17.8     76   

   origin                 car  
0       3         honda civic  
1       1      dodge aspen se  
2       1   ford granada ghia  
3       1  pontiac ventura sj  
4       1       amc pacer d/l

c.      Clean cars1 removing any unnamed columns (hing: loc might be helpful)



In [20]:
cars1.loc[:, ~cars1.columns.str.contains('^Unnamed')]

mpg  cylinders  displacement horsepower  weight  acceleration  model  \
0    18.0          8           307        130    3504          12.0     70   
1    15.0          8           350        165    3693          11.5     70   
2    18.0          8           318        150    3436          11.0     70   
3    16.0          8           304        150    3433          12.0     70   
4    17.0          8           302        140    3449          10.5     70   
..    ...        ...           ...        ...     ...           ...    ...   
193  24.0          6           200         81    3012          17.6     76   
194  22.5          6           232         90    3085          17.6     76   
195  29.0          4            85         52    2035          22.2     76   
196  24.5          4            98         60    2164          22.1     76   
197  29.0          4            90         70    1937          14.2     76   

     origin                        car  
0         1  chevrolet chevelle malibu  
1         1          buick skylark 320  
2         1         plymouth satellite  
3         1              amc rebel sst  
4         1                ford torino  
..      ...                        ...  
193       1              ford maverick  
194       1                 amc hornet  
195       1         chevrolet chevette  
196       1            chevrolet woody  
197       2                  vw rabbit  

[198 rows x 9 columns]

d.     How many observations exist in each dataset?



In [21]:
count_observations_cars1 = cars1.shape[0]
count_observations_cars2 = cars2.shape[0]

In [22]:
count_observations_cars1

198

In [23]:
count_observations_cars2

200

e.     Join cars1 and cars2 into one dataframe.



In [24]:
frames = [cars1, cars2]

In [25]:
cars = pd.concat(frames)

f.      Let’s add a column called owners consisting of random numbers from 15,000 to 73,000.

g.     Add it to the cars dataframe.

In [26]:
cars['owners'] = np.random.randint(15000, 73000, cars.shape[0])
#f and g done in one line

h.     Print the last five rows of the dataset.



In [27]:
cars.tail()

mpg  cylinders  displacement horsepower  weight  acceleration  model  \
195  27.0          4           140         86    2790          15.6     82   
196  44.0          4            97         52    2130          24.6     82   
197  32.0          4           135         84    2295          11.6     82   
198  28.0          4           120         79    2625          18.6     82   
199  31.0          4           119         82    2720          19.4     82   

     origin              car  Unnamed: 9  Unnamed: 10  Unnamed: 11  \
195       1  ford mustang gl         NaN          NaN          NaN   
196       2        vw pickup         NaN          NaN          NaN   
197       1    dodge rampage         NaN          NaN          NaN   
198       1      ford ranger         NaN          NaN          NaN   
199       1       chevy s-10         NaN          NaN          NaN   

     Unnamed: 12  Unnamed: 13  owners  
195          NaN          NaN   65707  
196          NaN          NaN   30949  
197          NaN          NaN   25362  
198          NaN          NaN   34634  
199          NaN          NaN   23907

i.       Which car has the min mpg?



In [28]:
min_mpg = cars[cars.mpg == cars.mpg.min()]
min_mpg['car']

28    hi 1200d
Name: car, dtype: object

j.       Which car has the max horsepower?



In [29]:
max_horsepower = cars[cars.horsepower == cars.horsepower.min()]
max_horsepower['car']

33                           amc gremlin
35             chevrolet chevelle malibu
37                           amc matador
47                      pontiac firebird
98                 chevrolet nova custom
99                            amc hornet
107                          amc gremlin
127                           amc hornet
128                       chevrolet nova
133    chevrolet chevelle malibu classic
169                          amc gremlin
191                     plymouth valiant
1                         dodge aspen se
29                plymouth volare custom
58                       plymouth volare
136                        mazda rx-7 gs
159                         datsun 200sx
Name: car, dtype: object